getgenv().Config = {
    Dashboard = {
        Enabled = false,
        SyncConfig = false,
        GroupName = "",
    },
    BabyFarm = true,
    AutoCertificate = false,
    PetFarm = {
        Enabled = true,
        FarmEggs = true,
        BuyEggs = true,
        EggTypes = {"endangered_2026_endangered_egg", "pet_recycler_2025_crystal_egg", "admin_abuse_egg_2026_egg"},
        BuyEggType = "any",
        MaxPets = 1,
        FarmUntilFullGrown = true,
        PrioritizeFriendship = false,
        SelectiveFarm = true,
        SelectedPetTypes = {
            "journey_2026_bison",
            "soggy_spring_2026_strawberry_shortcake_ducky",
            "soggy_spring_2026_unicorn_ducky",
            "endangered_2026_sea_turtle",
            "endangered_2026_blue_whale",
            "pet_progression_2026_purrowl",
            "admin_abuse_egg_2026_egg",
            "pet_recycler_2025_crystal_egg",
            "endangered_2026_endangered_egg",
            "admin_abuse_egg_2026_robot_chicken",
        },
    },
    AutoTrade = {
        Enabled = true,
        AutoAcceptTrades = false,
        AutoLeaveAfterTrades = false,
        Usernames = {
            "123_dEu63",
            "3grh2_hr",
            "udkc_jfx",
            "ya55min_570166",
            "1_flamingofan1011",
            "lucius236523",
            "Ba_byEr1c04",
            "TaughtGras_sNice91",
            "17k_vixxbe17",
            "3gSgs_6",
        },
        TradeMode = "specific",
        Categories = {"pets", "toys"},
        Items = {
            "soggy_spring_2026_glyptodon_ducky",
            "paint_2023_colored_hair_spray_sealer",
            "penguins_2025_dango_penguins",
            "food_pets_2026_dragonfruit_fox",
            "endangered_2026_silverback_gorilla",
            "endangered_2026_sea_turtle",
            "endangered_2026_blue_whale",
            "pet_progression_2026_purrowl",
            "lss_2026_glormy_crab",
            "admin_abuse_2025_sushi_penguin",
            "admin_abuse_egg_2026_robot_chicken",
            "soggy_spring_2026_unicorn_ducky",
            "soggy_spring_2026_strawberry_shortcake_ducky",
            "journey_2026_bison"
        },
        ItemCounts = {},
        GlobalPetFilter = {
            Versions = {},
            Ages = {},
        },
        PetFilters = {
            sugarfest_2026_dark_choccybunny = {
                regular = {6},
                neon = {},
                mega = {},
            },
            sugarfest_2026_mochi_meow = {
                neon = {6},
                mega = {},
            },
            sugarfest_2026_easter_bunny = {
                regular = {6},
                neon = {},
                mega = {},
            },
            endangered_2026_sea_turtle = {
                regular = {6},
                neon = {},
                mega = {},
            },
            endangered_2026_blue_whale = {
                regular = {6},
                neon = {},
                mega = {},
            },
            pet_progression_2026_purrowl = {
                regular = {6},
                neon = {},
                mega = {},
            },
            soggy_spring_2026_unicorn_ducky = {
                regular = {6},
                neon = {6},
                mega = {},
            },
            soggy_spring_2026_strawberry_shortcake_ducky = {
                regular = {6},
                neon = {},
                mega = {},
            },
            journey_2026_bison = {
                regular = {},
                neon = {6},
                mega = {},
            },
            soggy_spring_2026_glyptodon_ducky = {
                regular = {},
                neon = {6},
                mega = {},
            },
            journey_2026_nurse_shark = {
                regular = {6},
                neon = {},
                mega = {},
            },
        },
    },
    AutoNeon = {
        Enabled = true,
        MakeMega = false,
        NeonAll = false,
        SelectedPets = {
            "endangered_2026_sea_turtle",
            "endangered_2026_blue_whale",
            "soggy_spring_2026_unicorn_ducky",
            "soggy_spring_2026_glyptodon_ducky",
            "journey_2026_bison",
            "journey_2026_nurse_shark"
        },
        MaxPerType = {},
    },
    AutoPotion = {
        Enabled = true,
        SelectedPets = {
            "endangered_2026_sea_turtle",
            "endangered_2026_blue_whale",
            "pet_progression_2026_purrowl",
            "admin_abuse_egg_2026_egg",
            "soggy_spring_2026_unicorn_ducky",
            "soggy_spring_2026_strawberry_shortcake_ducky",
            "journey_2026_bison",
            "soggy_spring_2026_glyptodon_ducky",
            "journey_2026_nurse_shark"
        },
        PotionVersionFilter = {},
    },
    AutoBuy = {
        Enabled = true,
        SelectedItems = {"endangered_2026_endangered_egg", "soggy_spring_2026_rubber_ducky_box", "pet_recycler_2025_crystal_egg", "journey_2026_nurse_shark"},
        BuyAmounts = {},
    },
    AutoPay = {
        Enabled = false,
        TargetPlayer = {},
        Methods = {},
    },
    AutoOpen = {
        Enabled = true,
        Items = {"soggy_spring_2026_rubber_ducky_box"},
    },
    AutoRecycle = {
        Enabled = true,
        RarityFilter = {
            common = {"regular", "neon", "mega"},
            uncommon = {"regular", "neon", "mega"},
            rare = {"regular", "neon", "mega"},
            ultra_rare = {"regular", "neon", "mega"},
        },
        AgeFilter = {},
        ExcludedPets = {"soggy_spring_2026_unicorn_ducky", "soggy_spring_2026_strawberry_shortcake_ducky", "soggy_spring_2026_glyptodon_ducky", "journey_2026_bison"},
    },
    IdleProgression = {
        Enabled = true,
        SelectedPets = {"endangered_2026_endangered_egg", "pet_recycler_2025_crystal_egg", "admin_abuse_egg_2026_egg"},
        ExcludedPets = {
            "sugarfest_2026_gumball_caterpillar",
            "penguins_2025_dango_penguins",
            "food_pets_2026_dragonfruit_fox",
            "endangered_2026_silverback_gorilla",
            "lss_2026_glormy_crab",
            "sugarfest_2026_mochi_meow",
            "endangered_2026_sea_turtle",
            "endangered_2026_blue_whale",
            "pet_progression_2026_purrowl",
            "admin_abuse_2025_sushi_penguin",
            "admin_abuse_egg_2026_robot_chicken",
        },
        PriorityOrder = {"regular"},
        PenVersionFilter = {},
    },
    AccountManager = {
        Enabled = false,
        Tool = "",
        Yummy = {
            Action = "completed",
            Reason = "Done",
        },
        FarmSync = {
            Action = "completed",
            FromFolderId = "",
            ToFolderId = "",
            ChangeWithoutReplacement = false,
            ConfigId = nil,
            ApiKey = "",
        },
        Triggers = {
            AfterTradeComplete = false,
            MinBucks = 0,
            MinPotions = 0,
        },
    },
    Settings = {
        ShowOverlay = true,
        ReduceGraphics = true,
        FPSCap = 2,
        LureId = "ice_dimension_2025_ice_soup_bait",
        TradeInvites = "Everyone",
    },
    Webhook = {
        Enabled = false,
        URL = "",
        PetUnlock = {
            Enabled = false,
            URL = "",
            FilterRarities = {},
        },
    },
    TaskExclusion = {
        Enabled = false,
        ExcludedTasks = {},
    },
}
